### ISSUE TITLE
Filter which data source URLs are updated

### ISSUE THREAD

**Issue by tonybaines** [yusufugurozbek/testcontainers-port-updater#116]
Excellent plugin, really useful for debugging.

**Is your feature request related to a problem? Please describe.**
I think all localhost JDBC URLs with non-default ports are updated with the testcontainers port number - that's a bit of a problem for me with other datasources configured for alternative ports e.g. `jdbc:postgresql://localhost:15432/postgres` will be updated with the most recent testcontainers port to e.g.  `jdbc:postgresql://localhost:49132/postgres`

**Describe the solution you'd like**
A documented way to identify the testcontainers data source, maybe a **required** query parameter `?testcontainers=true` would work

**Describe alternatives you've considered**
I've discovered by coincidence that if I add a query parameter to a JDBC URL it's never updated, so  `jdbc:postgresql://localhost:15432/postgres?testcontainers=false` won't ever be updated.  This works but seems fragile (what if you add support for URLs with parameters) and I need to remember for each new data source

**Comment by yusufugurozbek** [comment]
Hello @tonybaines 👋🏼 

Thanks again for using the plugin and raising an issue. I used your idea and released a new version (v1.0.0). Now you can select your match mode via [settings](https://github.com/yusufugurozbek/testcontainers-port-updater/tree/v1.1.0#--select-match-mode). The new version should be available in the next few days. 

Looking forward to hearing your feedback.

Greetings 🖐🏼

**Comment by yusufugurozbek** [comment]
Hello @tonybaines 👋🏼 

Thanks again for using the plugin and raising an issue. I used your idea and released a new version (v1.0.0). Now you can select your match mode via [settings](https://github.com/yusufugurozbek/testcontainers-port-updater/tree/v1.1.0#--select-match-mode). The new version should be available in the next few days. 

Looking forward to hearing your feedback.

Greetings 🖐🏼

**Comment by tonybaines** [comment]
Perfect - just what I needed.  Thanks for the quick enhancement

**Comment by yusufugurozbek** [comment]
Nice to hear that 🤗
