### ISSUE TITLE
Port for database instance is not updated

### ISSUE THREAD

**Issue by androa** [yusufugurozbek/testcontainers-port-updater#147]
**Describe the bug**
The port does not get updated. The notification is not popping up either.

I've tried to figure out why and I can't understand anything else than that the IntelliJ `ConsoleFilterProvider` or the `getMaybeLocalDataSource()` is not firing correctly.

**To Reproduce**
I run my tests which outputs this to the logs:
`{"@timestamp":"2023-07-18T16:13:11.315968+02:00","@version":"1","message":"Database: jdbc:postgresql://localhost:32799/test (PostgreSQL 15.2)","logger_name":"org.flywaydb.core.internal.database.base.BaseDatabaseType","thread_name":"Test worker","level":"INFO","level_value":20000}`

My datasource in IntelliJ is configured with this URL: `jdbc:postgresql://localhost:32791/test`.

**Expected behavior**
The port to be updated.

**Screenshots**
<img width="812" alt="Screenshot 2023-07-18 at 16 21 07" src="https://github.com/yusufugurozbek/testcontainers-port-updater/assets/588046/f7de77a5-d140-49df-8dbc-c9825abe91bc">
<img width="1012" alt="Screenshot 2023-07-18 at 16 21 38" src="https://github.com/yusufugurozbek/testcontainers-port-updater/assets/588046/e08ba780-5732-4d0d-b8e6-d81f33d0ef4b">
<img width="990" alt="Screenshot 2023-07-18 at 16 22 15" src="https://github.com/yusufugurozbek/testcontainers-port-updater/assets/588046/30ad638c-fdbe-422f-b360-91133116625a">

**IntelliJ version**
```
IntelliJ IDEA 2023.1.4 (Ultimate Edition)
Build #IU-231.9225.16, built on July 12, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1

Kotlin: 231-1.8.21-IJ9225.16
```

**Comment by yusufugurozbek** [comment]
Howdy @androa 🖐🏼

I assume you have a custom logging configuration. Could you please share it with me? I need to reproduce that on my local machine.

Greetings

**Comment by androa** [comment]
Yep, that's right. This is the log configuration we run: https://github.com/navikt/rapids-and-rivers/blob/master/src/main/resources/logback.xml. Added a PR to your demo-repository with that (slightly simplified) setup.

The plugin has worked marvels with this configuration for years.

**Comment by yusufugurozbek** [comment]
The new release (v1.1.2) should solve your issue. Please check the settings and mark your project logging format as JSON.

**Comment by androa** [comment]
Thank you! Tested it now and it seems to work now. But I'm not getting any notifications, even if it is checked off in the settings.

**Comment by androa** [comment]
It was indeed the notification settings that was set to no popup. This seems to be the default when the plugin is installed. Thank you again. This plugin is one of the most time saving plugins out there 🚀
