### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.2

### ISSUE THREAD

**Issue by mkobel** [yusufugurozbek/testcontainers-port-updater#154]
The currently latest version 1.1.1 mentions a compatibility range of 222—231.* / IntelliJ IDEA Ultimate — 2022.2 — 2023.1.5

https://plugins.jetbrains.com/plugin/17116-testcontainers-port-updater/versions

**Comment by stevenhurth** [comment]
@yusufugurozbek Do you know if there are plans to upgrade this plugin to work with 2023.2+?

**Comment by yusufugurozbek** [comment]
Guys thanks for using the plugin. The new release (v1.1.2) should solve your issue. Looking forward to hearing your feedback.

**Comment by stevenhurth** [comment]
That is great to hear, thank you much!

Like someone else said, "When you need it, you need it"

Awesome work :)
