### ISSUE TITLE
Upgrade plugin to find not only postgres

### ISSUE THREAD

**Issue by NewbieProger** [yusufugurozbek/testcontainers-port-updater#167]
In nowdays we use a lot of DB's but as I can understand ur plugin works only with Postgre. Can u upgrade it for each container which supports https://java.testcontainers.org/features/creating_container/ ?

**Comment by yusufugurozbek** [comment]
Hello @NewbieProger,

Thanks for reaching me. 

The plugin is not specified for only PostgreSQL usage. You can use it on any container. As mentioned on [the readme file](https://github.com/yusufugurozbek/testcontainers-port-updater#usage) there are 2 requirements. There should be a log that matches your plugin configuration and a data source on IntelliJ.

If you can share your use case in detail, I will try to support you.

Greetings 👋🏼

**Comment by yusufugurozbek** [comment]
Hello @NewbieProger,

As I haven't received any updates from you in a while, I have decided to close the issue. If you still require assistance, please re-open it.

Greetings 🖐🏼
