### ISSUE TITLE
Plugin incompatible with the new build

### ISSUE THREAD

**Issue by stevenhurth** [yusufugurozbek/testcontainers-port-updater#204]
I updated intellij today, and it appears this plugin is not compatible with intellij build 241.14494.240.

(Edit, changed build number)

**Comment by yusufugurozbek** [comment]
Hello all,

Many thanks for using the plugin. The next release should fix this issue. 

If you like the Testcontainers Port Updater plugin, please don't forget to give it a star on [GitHub](https://github.com/yusufugurozbek/testcontainers-port-updater) and write a review or rate on [JetBrains](https://plugins.jetbrains.com/plugin/17116-testcontainers-port-updater).

Greetings 👋🏼
