### ISSUE TITLE
Incompatible with 2024.3

### ISSUE THREAD

**Issue by stevenhurth** [yusufugurozbek/testcontainers-port-updater#254]
I updated IntelliJ today, and it appears this plugin is not compatible with IntelliJ build 243.21565.193.

**Comment by yusufugurozbek** [comment]
Hello @stevenhurth,

Many thanks for using the plugin. The next release should fix this issue. 

If you like the Testcontainers Port Updater plugin, please don't forget to give it a star on [GitHub](https://github.com/yusufugurozbek/testcontainers-port-updater) and write a review or rate on [JetBrains](https://plugins.jetbrains.com/plugin/17116-testcontainers-port-updater).

Greetings 👋🏼
